### ISSUE TITLE
feature request: overall amount controls

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#11]
It would be very handy to have 2 new sliders:

- one for the overall amp change amount, from 0 to say 4, default 1
- one for the overall time change amount, same range.

When the (time/amp) amount is 0, the (time/amp) data is unchanged, just the latency is applied.
When the amount is 1, the plugin functions as it does now.
When the amount is higher than 1, the changes are scaled by the slider, clipping the velocity at 127.

The main use cases are:

- Automation. You could get the same effect without this feature, but just like with the swing sliders, it can be nice to automate from no change to full effect without having to automate all the sliders.
- For subtle changes: design a pattern with amount turned up a bit and then use it at 1.

In case the only change you made is one or both of the swing sliders, these new sliders are superfluous, they are only needed when there are other changes.

edit: I guess negative amounts could come in useful as well.

**Comment by sjaehn** [comment]
Do you mean "dry/wet" sliders for MIDI ? With values which exceed the 0 (dry) to 1 (wet) limit ?

**Comment by magnetophon** [comment]
Yes. As a matter of fact, the first title I typed had "dry/wet" in it!  :)

I though that would be a confusing way of saying it.  :shrug:

**Comment by sjaehn** [comment]
Added to TODO. I will call it "amp master" and "steps master" (already on GUI).

The amp master will be easy to make. Even with values > 1.0 and values < 0.0.

The steps/swing master will really be tricky. At least with values outside the 0.0 .. 1.0 range. Values > 1.0 (or values < 0.0) may result in invalid step positions (= overtaking the respective neighbor steps). This condition needs to be handled. Also the steps master will take effect on the plugin latency. And what will be the result if you make a change during playback?

**Comment by magnetophon** [comment]
Cool!
A range from 0 to 1 for the steps master seems like it would get us 80% of the results for 20% of the effort (said the armchair quarterback).
So just go with that then?

**Comment by sjaehn** [comment]
I like the idea with values > 1.0 and values < 0.0 for the steps master too. But I'll start with 0.0 .. 1.0 range.

**Comment by sjaehn** [comment]
I though again about how to name this effect. 

My idea to call it "master" is bad. What would you expect to hear if a master value is at 0 ? Nothing. But you get the unchanged input signal here.

"Amount" is not clear enough. This would need further explanations.

"Mix" is better. But still, further explanations are needed (mixing what?)

"Dry/wet" would theoretically be the best explanation. But I heard "dry/wet" only for audio signals before. Maybe I'm wrong.

Any (other) idea ?

**Comment by magnetophon** [comment]
I agree about master and amount.

To me, mix and dry/wet suggest you'll hear the mix of both signals, both the time-shifted and the original signal.
So IOW: I think those are confusing names too.

I think amount is the least bad, but we can come up with something better.

**Comment by magnetophon** [comment]
Strength?

**Comment by sjaehn** [comment]
You are right about mix and dry/wet.

"Amp process amount (or strength)* and "Step process amount (or strength)" would be better. But too long.

**Comment by sjaehn** [comment]
Sliders added in e6bcc76889b336c1eb17e91c5f469e91b92995a6. I preliminarily used "Amp process" and "Step process". But I'm still open for any better idea.
