### ISSUE TITLE
feature request: linked instances 

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#15]
It would be great if we could link up the controls of various instances of the plugin.
That way you could, for example, tweak the swing amount of a whole song at once.

[CHOWTapeModel](https://github.com/jatinchowdhury18/AnalogTapeModel) has this, and calls it "mix groups".
It works as follows: the plugin has a "mix group" drop-down, with the choices  "none, 1, 2, 3 and 4".
By default it's one "none" and no controls are linked.
When you set it to "1", the controls are linked to all other plugin instances that have it set to "1" as well.

Thank you for considering!

**Comment by sjaehn** [comment]
Challenging. At least for me. I never tried to get access to different instances of the same plugin. Maybe via (ugly) global variables? I'm not sure. Any other ideas? I remember there was a (bit) similar request by @iurie-sw about the plugin instance ID in the LV2 devel mailing list.

**Comment by magnetophon** [comment]
Great that you seem to like the idea!

Going by [the commit messages](https://github.com/jatinchowdhury18/AnalogTapeModel/search?q=mix+group&type=commits), CHOWTapeModel did it via OSC at first and at the moment they do it through a shared resource pointer. 

Hope that helps. If not, maybe @jatinchowdhury18 can chip in?

**Comment by jatinchowdhury18** [comment]
Haha, definitely don't use OSC for this type of thing, that was a pretty rookie mistake :)!

I ended up using the JUCE [`SharedResourcePointer`](https://github.com/juce-framework/JUCE/blob/master/modules/juce_core/memory/juce_SharedResourcePointer.h), which isn't too compilcated, so you could probably roll your own (or just copy their implementation, under GPL).

The basic design pattern was to have a `SharedData` class (one instance shared by all the plugin instances) that stores the parameter values for each "mix group" and the IDs of the plugin in each mix group, and a `Controller` class (each plugin instance gets it's own) that listens for parameter changes, and passes data back and forth between the SharedData and the rest of the plugin.

My implementation is all in [this directory](https://github.com/jatinchowdhury18/AnalogTapeModel/tree/master/Plugin/Source/MixGroups), please let me know if you have any questions, or if there's any way I can help!

**Comment by sjaehn** [comment]
Thanks for your tips. I also thought about it for the whole day. Although we use different tools (you JUCE, me directly targeting LV2), I ended up with similar ideas as you described. It's quite clear that it must be sth. in the global context of the plugin (not in an instance). One idea (very similar to yours) is to globally share the plugin data. The other one would be a simple std::vector containing pointers to all active plugin instances. Anyway both approaches will only work for hosts which do not sandbox the plugin instances.

But first of all I will have a more detailed look to your code to understand the way you gone.

**Comment by sjaehn** [comment]
Now I found some time to get an overview about how CHOWTapeModel handles shared data. It is programmed in a clear way. I like it. And it is similar to my idea.

The pitfalls are beyond the use of shared data. The main problems would be the LV2 `control_port`s I used for all the sliders (read only from the plugin side) and the backward compatibility if I have to switch to LV2 parameters (read and write, but limited support by the hosts). Thus, my solution wouldn't be as smart & slim as those by @jatinchowdhury18 .

**Comment by magnetophon** [comment]
Thanks a lot for looking into this!

I use B.Schaffl in almost all my music now!

**Comment by sjaehn** [comment]
Something like this: 7389f41c18f4162c9e81c1bfd84574b9c9b3e020 ?

It's experimental, yet. Just a preview. Not all features are implemented. Like state:save and state:restore (required for close & reopen plugin). And it might be a bit buggy. I still have to optimize signal routing. If I would have planned the implementation of such a feature before, I would have done signal routing between DSP and GUI in a less complicated way than I did. And now I the shared data routing on top.

**Comment by magnetophon** [comment]
Cool! Thanks a lot!  :)

As you said: close and reopen messes things up.
Also: it works in Ardour, but when I open the plugin twice in jalv.gtk, it does not link.
Not that I think it will be used like that, but it might be useful debugging info for you.
There is a bit of lag between the master and slave. Doesn't matter, just reporting.

I've found no other bugs yet.

**Comment by sjaehn** [comment]
... also not supported yet: shape.

I tested it in ardour6 and carla2.3. Jalv will not work as jalv only hosts one plugin instance. Of course, you can start different instances of jalv (each hosting one plugin instance). But this is sth. different. And this will not work. As each jalv instance individually loads the plugin file (and its individual shared data).

The time lag is expected if you think about control routing:
1. Drag a slider in the master GUI. But is GUI is usually called 20 to 60 times per seconds. = 15 to 50 ms latency.
2. GUI sends data via the host to the DSP. DSP run() stores the data to the shared data. DSP run() is usually called every 5 to 20 ms depending on your settings (buffer_size / frame_rate). += 5 to 20 ms latency.
3. If the slave is routinely called before the master, the slave can get the updated shared data only in the next call of DSP run(). += 5 to 20 ms latency.
4. And the slave DSP has to send the data to the slave GUI. += 15 to 50 ms latency.

**Comment by sjaehn** [comment]
State save / restore added in e5fc336d65e0442cc2dbb9ed698825bb1c583d77 .

Now working on storing the shape into the shared data.

**Comment by sjaehn** [comment]
Some of the reported lag problems are fixed in 01b362341ef10123a912a52d556784233d5266e6 . One less data transfer step.

**Comment by sjaehn** [comment]
And finally shape added to shared data in 48b43a352b25dd533a4a0cbff6e69ffbc8ca4f92 . Some testing before release 1.4.0 is needed. @magnetophon , let me know if you find some bugs.

**Comment by magnetophon** [comment]
Perfect; thank you!

No bugs so far, I'll keep you up to date!
