### ISSUE TITLE
UX issues with floating point inputs

### ISSUE THREAD

**Issue by rulatir** [sjaehn/BSchaffl#20]
There are a couple of UX issues with numeric input controls recently employed to implement #19.

1. The controls don't seem to handle Home, End and arrow key events. In order to position the caret on the desired digit, one must use the mouse. The unhandled key events propagate to the main DAW window (Ardour6 in my case) and move the playhead around.

2. Possibly locale related (I'm using Polish locale): I cannot enter a decimal comma if I accidentally erase it. Neither the period key (letter block or numeric block) nor the comma key works. This makes the comma "precious", and combined with point 1. it makes using mouse for positioning the caret unavoidable.

I'm on Linux/KDE.

**Comment by rulatir** [comment]
Hmm, looks like `Label` tries to handle those keys, so perhaps it's Ardour6's fault, it could be processing key events before plugins.

**Comment by rulatir** [comment]
Aaah, there's this green keyboard icon in every Ardour plugin dialog that controls where the key events go first. Never had to use it before!

**Comment by rulatir** [comment]
Reopening because I think Label should also handle Home and End, and the issue with the decimal point remains. The latter is probably still environment's fault because you are clearly handling the whole printable ASCII range, though it might be worth debugging in Ardour to see whether those keystrokes don't come at all, or come weird. The former however, you aren't handling Home or End.

**Comment by sjaehn** [comment]
Key grabbing is an Ardour-related problem. But you _should_ have found the solution. I have to admit that I sometimes experienced that Ardour kept grabbing keys even if the keyboard icon was clicked.

Home and End are good feature requests. Thanks.

FYI, you can use both, decimal comma or decimal point, independent from your locale settings. Both are parsed.

**Comment by sjaehn** [comment]
Support keys HOME and END just pushed to master.
