### ISSUE TITLE
No velocity change

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#3]
After some more playing I found out I couldn't change the velocity, no matter what setting I tried.
Is that already implemented?

**Comment by sjaehn** [comment]
This should work with b11e72b3b67f2cf274e6c14ed25f127d6533982e . And this can also be a nice demonstration of what can happen if the NOTE_ON appears in the wrong step... :-(

**Comment by magnetophon** [comment]
Yes, fixed!  You are quick! :rocket: 
You also seem to have fixed bug where the first bar of the song was not  changed.
