### ISSUE TITLE
Feature request: level swing 

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#4]
This would do for level what the current swing slider does for time.

With the slider in the middle, the midi is unchanged.
With the slider all the way to the left, notes falling in the period of the even notes of the pattern have velocity 0 and the notes falling in the period of the uneven notes have unchanged velocity.
With the slider all the way to the right, the even notes are unchanged and the uneven notes are 0.

Its easy enough to do by hand, at most move 8 sliders, but this new slider would be great for automating. 

You can probably come up with a better name for this feature.  ;) 

Of course it would be just as useful for B.Choppr.

**Comment by sjaehn** [comment]
Thanks, good idea. Added to TODO.

**Comment by sjaehn** [comment]
Feature added in 672af69c766bf3f7b8464fd86491f6512e2ec39b .

**Comment by magnetophon** [comment]
Oh, nice!!!

When I requested the feature, the auto/manual problem of the faders crossed my mind, and I thought we'd eventually need something similar what the timing sliders have.
The scaling faders is a much more elegant and visually clear solution.  :heart:   

Also the (log?) scaling on the amp swing slider is great.
That level of attention to detail makes software a joy to use.  :100:
