### ISSUE TITLE
Assign to step changes timing

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#6]
Maybe I misunderstood what it is supposed to do.
I thought it would assign a note to a step in order to apply that step's level to it.
It seems to change the timing too.

**Comment by sjaehn** [comment]
Both is supported. Assignment and timing. Therefore two sliders.

**Comment by magnetophon** [comment]
Yes, that's what I thought, but Assign changes the timing for me.

**Comment by sjaehn** [comment]
This shouldn't happen.

**Comment by sjaehn** [comment]
Let's take your SchafflDemo as an example (with assignment on and range set to a low value of some 0.1). Input 16 symmetric short ticks per bar. This means that note 1 starts at bar position 0.000, note 2 at 0.0625, note 3 at 0.125, ...

You divided each bar into 11 steps. This means that each input step takes some 0.09 bars. 

Therefore note 1 and note 2 drops into step 1 and note 3 into step 2... Note 1 and note 2 are amplified with amp of step 1 (and you can easily hear both of them). Note 3 is amplified with amp of step 2 (you can gently hear). Note 1 and note 2 are stretched to 0.0112-0.0291 and 0.0832-0.1012, respectively (latency = 0.0112). Note 3 is squeezed to 0.1438-0.1565.

The data and what I hear fit nicely to the theory. Thus, it works.

But there are two pitfalls. (1) If you switch off assignment, the note can drop into the wrong step. As you know. And this may *sound* like a timing change. Especially if all notes have the same pitch. (2) If the range is too high, a middle note can be assigned to the next step. This may easily happen with your 16/11 pattern. And also this may *sound* like a time change.

**Comment by magnetophon** [comment]
Ah, yes, now I get it.
My mental model was indeed off, and yes, I was hearing velocity changes and mistaking them for timing changes.

Sorry for the noise!
