### ISSUE TITLE
feature request: all controls visible all the time

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#8]
The plugin is not big enough to show both the  help text and the controls at the same time, and if you'd make it bigger, it would be a bit overwhelming.
Especially if you keep implementing all the extra controls I keep asking for!  ;)

The current solution with different categories of controls shown together with the help may be ideal for newcomers, but leads to unneeded clicking, hence a slower creative process.

I propose to have all the controls visible all the time, but have the help text pop in and out of existence, either by floating over the controls with the mouse, as [x42-plugins](https://github.com/x42/x42-plugins) does it, or by clicking on a button, like in the wonderful [Uhhyou Plugins](https://github.com/ryukau/LV2Plugins/).

**Comment by sjaehn** [comment]
Hover text would be easy to implement, but this wouldn't be the solution.

There will be 17 additional switches in the midi channel filter section and at least 8 additional switches in the midi message filter section. And there are even more features scheduled. I think there wouldn't be enough space for all of them even if I remove the help text.

IMO, the users focus should be on everything that directly effects the sound (amp, stretch, swing, ...) but not on the settings (latency, quantization range, ...).

**Comment by magnetophon** [comment]
Fair enough.
